project:
  type: website

execute:
  freeze: auto

website:
  title: "Amine Hochlef"
  site-url: https://www.aminehochlef.github.io
  description: "The legendry blog of Amine Hochlef"
  # margin-header: subscribe.html
  page-navigation: false
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - icon: rss
        href: blog.xml
    toggle-position: right
  page-footer: 
      left: "Copyright 2024, Amine Hochlef" 
  back-to-top-navigation: false
format:
  html:
    allow-html: true
    theme: sandstone
    css: 
      - styles.css
    toc: true




